/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\chair.glb -o src\components\scene\ChairModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    OBJ_HighTechChair_base: THREE.Mesh
  }
  materials: {
    MAT_HighTechChair_base: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chair.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.OBJ_HighTechChair_base.geometry} material={materials.MAT_HighTechChair_base} />
    </group>
  )
}

useGLTF.preload('/chair.glb')
