/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\iphone.glb -o src\components\scene\IPhoneModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    main_1: THREE.Mesh
    camera_1: THREE.Mesh
    glass_1: THREE.Mesh
    apple_1: THREE.Mesh
  }
  materials: {
    phone16pro: THREE.MeshStandardMaterial
    phone16pro_transparent: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/iphone.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.main_1.geometry} material={materials.phone16pro} />
      <mesh geometry={nodes.camera_1.geometry} material={materials.phone16pro} />
      <mesh geometry={nodes.glass_1.geometry} material={materials.phone16pro_transparent} />
      <mesh geometry={nodes.apple_1.geometry} material={materials.phone16pro} />
    </group>
  )
}

useGLTF.preload('/iphone.glb')
