/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\lamp.glb -o src\components\scene\LampModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Retopo_Circle: THREE.Mesh
    Retopo_Cylinder005: THREE.Mesh
    Roundcube: THREE.Mesh
    Circle001: THREE.Mesh
    Circle002: THREE.Mesh
    Cylinder001: THREE.Mesh
    Retopo_Circle005: THREE.Mesh
    mesh004: THREE.Mesh
    mesh004_1: THREE.Mesh
    Sphere: THREE.Mesh
    Retopo_Cylinder002: THREE.Mesh
  }
  materials: {
    madera: THREE.MeshStandardMaterial
    ['metal tubos']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    luz: THREE.MeshStandardMaterial
    cortin: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/lamp.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.madera} position={[1.074, 7.075, 0]} />
      <mesh geometry={nodes.Retopo_Circle.geometry} material={materials.madera} position={[0, 0.166, 0]} />
      <mesh geometry={nodes.Retopo_Cylinder005.geometry} material={materials.madera} position={[1.593, 6.16, 0.015]} />
      <mesh geometry={nodes.Roundcube.geometry} material={materials.madera} position={[-1.78, 10.661, 0.008]} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['metal tubos']} position={[0, 4.834, 0]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['metal tubos']} position={[1.078, 8.199, -0.001]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['metal tubos']} position={[1.591, 6.578, 0]} />
      <mesh geometry={nodes.Retopo_Circle005.geometry} material={materials['metal tubos']} position={[-1.782, 11.205, 0.003]} />
      <group position={[-1.784, 10.458, 0.008]}>
        <mesh geometry={nodes.mesh004.geometry} material={materials.madera} />
        <mesh geometry={nodes.mesh004_1.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials.luz} position={[-1.78, 8.475, -0.064]} />
      <mesh geometry={nodes.Retopo_Cylinder002.geometry} material={materials.cortin} position={[-1.785, 8.475, -0.009]} />
    </group>
  )
}

useGLTF.preload('/lamp.glb')
