/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\monitor.glb -o src\components\scene\MonitorModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh
    Circle: THREE.Mesh
    Cube: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Curve013: THREE.Mesh
    Circle001: THREE.Mesh
    Cube005: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cube001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Curve001: THREE.Mesh
    Curve002: THREE.Mesh
    Curve003: THREE.Mesh
    Curve004: THREE.Mesh
    Curve005: THREE.Mesh
    Curve006: THREE.Mesh
    Curve007: THREE.Mesh
    Curve008: THREE.Mesh
    Curve009: THREE.Mesh
    Curve010: THREE.Mesh
    Curve011: THREE.Mesh
    Curve012: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Plane001: THREE.Mesh
  }
  materials: {
    ['Brushed metal']: THREE.MeshPhysicalMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Wood Black UA.002']: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    ['Wood Black UA']: THREE.MeshStandardMaterial
    ['Body.001']: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    ['Brushed metal.001']: THREE.MeshPhysicalMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Wood Black UA.003']: THREE.MeshStandardMaterial
    ['Screen.001']: THREE.MeshStandardMaterial
    ['Wood Black UA.004']: THREE.MeshStandardMaterial
    ['Body.002']: THREE.MeshStandardMaterial
    ['Gold.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    wall: THREE.MeshStandardMaterial
    ['SVGMat.002']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/monitor.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.012, 0.016, 0.001]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Curve.geometry} material={materials['Brushed metal']} position={[1.67, 2.869, 0.274]} rotation={[Math.PI / 2, 0.196, -Math.PI / 2]} scale={0.49} />
        <mesh geometry={nodes.Circle.geometry} material={materials['Material.004']} position={[-0.102, 0.477, -0.068]} scale={0.501} />
        <mesh geometry={nodes.Cube.geometry} material={materials['Wood Black UA.002']} position={[0.012, 0.415, 2.645]} rotation={[0, 0.001, 0]} scale={0.368} />
        <group position={[1.135, 5.658, 0.075]} rotation={[0, 0, 0.105]} scale={[0.212, 3.168, 5.928]}>
          <mesh geometry={nodes.Cube003_1.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Cube003_2.geometry} material={materials['Wood Black UA']} />
        </group>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Body.001']} position={[0.012, 1.974, -0.001]} scale={[0.607, 0.341, 0.607]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Gold} position={[0.012, 1.145, -0.001]} scale={0.556} />
      </group>
      <group position={[-1.896, 0, 0.58]}>
        <mesh geometry={nodes.Curve013.geometry} material={materials['Brushed metal.001']} position={[1.67, 2.869, 0.274]} rotation={[Math.PI / 2, 0.196, -Math.PI / 2]} scale={0.49} />
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.003']} position={[-0.102, 0.477, -0.068]} scale={0.501} />
        <mesh geometry={nodes.Cube005.geometry} material={materials['Wood Black UA.003']} position={[0.012, 0.415, 2.645]} rotation={[0, 0.001, 0]} scale={0.368} />
        <group position={[1.135, 5.658, 0.075]} rotation={[0, 0, 0.105]} scale={[0.212, 3.168, 5.928]}>
          <mesh geometry={nodes.Cube007.geometry} material={materials['Screen.001']} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials['Wood Black UA.004']} />
        </group>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Body.002']} position={[0.012, 1.974, -0.001]} scale={[0.607, 0.341, 0.607]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Gold.001']} position={[0.012, 1.145, -0.001]} scale={0.556} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.339, 2.107, 0]} scale={0.353} />
      <group scale={33.145}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.wall} />
      </group>
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} position={[0.024, 0.54, -0.358]} scale={5.668} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.002']} position={[0.024, 0.54, 0.288]} scale={5.668} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.002']} position={[-0.135, 0.54, -0.305]} scale={5.668} />
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.002']} position={[0.189, 0.54, 0.254]} scale={5.668} />
      <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.002']} position={[-0.251, 0.54, -0.189]} scale={5.668} />
      <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.002']} position={[0.308, 0.54, 0.135]} scale={5.668} />
      <mesh geometry={nodes.Curve007.geometry} material={materials['SVGMat.002']} position={[-0.299, 0.54, -0.035]} scale={5.668} />
      <mesh geometry={nodes.Curve008.geometry} material={materials['SVGMat.002']} position={[0.347, 0.54, -0.035]} scale={5.668} />
      <mesh geometry={nodes.Curve009.geometry} material={materials['SVGMat.002']} position={[-0.261, 0.54, 0.135]} scale={5.668} />
      <mesh geometry={nodes.Curve010.geometry} material={materials['SVGMat.002']} position={[0.3, 0.54, -0.189]} scale={5.668} />
      <mesh geometry={nodes.Curve011.geometry} material={materials['SVGMat.002']} position={[-0.14, 0.54, 0.254]} scale={5.668} />
      <mesh geometry={nodes.Curve012.geometry} material={materials['SVGMat.002']} position={[0.183, 0.54, -0.305]} scale={5.668} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[9.172, 19.019, -12.782]} rotation={[-3.109, -0.8, 0.723]} scale={[6.192, 0.729, 0.729]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[9.522, 19.019, -9.783]} rotation={[-3.086, -0.75, 0.863]} scale={[6.192, 0.729, 0.729]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[37.063, 20.5, 0]} rotation={[0, 0, -Math.PI / 2]} scale={24.276} />
    </group>
  )
}

useGLTF.preload('/monitor.glb')
