/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree gulb.glb -t -o src/components/scene/Tree.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tree001: THREE.Mesh
    leaves001: THREE.SkinnedMesh
    bone000000: THREE.Bone
  }
  materials: {
    ['Tree bark']: THREE.MeshStandardMaterial
    ['Graswald_CreepingBentgrass_Low_Cycles/Eevee.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/models/tree gulb.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -1.359, 0]}>
        <primitive object={nodes.bone000000} />
        <mesh geometry={nodes.tree001.geometry} material={materials['Tree bark']}>
          <skinnedMesh geometry={nodes.leaves001.geometry} material={materials['Graswald_CreepingBentgrass_Low_Cycles/Eevee.001']} skeleton={nodes.leaves001.skeleton} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tree gulb.glb')
